#!/usr/bin/env bash
# =============================================================================
# Umay — bring up the backend + its database ALONGSIDE whatever already runs on
# the box, without touching it.
#
# Written for 188.137.231.252, where ana-bala.kz is already served by a live
# Aiti.kz CRM (its own Caddy container on 80/443, its own self-hosted Supabase).
# `bootstrap.sh` assumes a FRESH box and would take those ports and overwrite
# /etc/caddy/Caddyfile — i.e. destroy a running product. This script does not:
#
#   - our Postgres and our backend run as two new containers, joined to the
#     CRM's existing Docker network so its Caddy can reach ours by name;
#   - nothing is published to the host, so no port can collide;
#   - no existing container, volume, image or config file is modified.
#
# Routing (which hostname/paths reach us) is a SEPARATE, reversible step — see
# deploy/landing-route.md. This script only makes the backend exist and answer.
#
# Idempotent: re-run after a `git pull` to pick up new code.
#
#   ssh root@HOST 'bash /opt/umay/deploy/landing-stack.sh'
# =============================================================================
set -euo pipefail

APP_DIR="${APP_DIR:-/opt/umay}"
NETWORK="${NETWORK:-supabase_default}"   # the CRM's compose network
DB_NAME=umay
DB_USER=umay
ENV_DIR=/etc/umay
ENV_FILE="$ENV_DIR/backend.env"
NODE_IMAGE=node:24-alpine
PG_IMAGE=postgres:15-alpine
REDIS_IMAGE=redis:7-alpine

echo "==> Preconditions"
docker network inspect "$NETWORK" >/dev/null 2>&1 || { echo "network $NETWORK missing"; exit 1; }
[ -d "$APP_DIR/packages/backend" ] || { echo "$APP_DIR is not the repo"; exit 1; }
[ -f "$APP_DIR/packages/backend/landing/index.html" ] || {
  echo "landing not built in this checkout — run tools/build-landing.mjs and commit"; exit 1; }

# ---- Secrets -----------------------------------------------------------------
# Generated HERE, on the box, so no credential is ever typed into a chat, a
# command line or the repo. Written once; re-runs reuse the same file.
mkdir -p "$ENV_DIR"
if [ ! -f "$ENV_FILE" ]; then
  echo "==> Generating $ENV_FILE"
  DB_PASS="$(head -c 24 /dev/urandom | base64 | tr -d '/+=' | head -c 28)"
  cat > "$ENV_FILE" <<EOF
# Umay backend — generated by deploy/landing-stack.sh. Keep chmod 600.
DATABASE_URL=postgres://$DB_USER:$DB_PASS@umay-db:5432/$DB_NAME
POSTGRES_PASSWORD=$DB_PASS
# Bind all interfaces INSIDE the container. Nothing is published to the host,
# so the only thing that can reach this port is another container on $NETWORK.
HOST=0.0.0.0
PORT=8080
REDIS_URL=redis://umay-redis:6379
# NODE_ENV is deliberately NOT 'production': the boot guard refuses to start
# while staff auth is still the x-staff-role header stub. The mitigation is at
# the edge — the reverse proxy exposes ONLY the landing page and the lead form,
# never /admin/* or the app API. See deploy/landing-route.md.
EOF
  chmod 600 "$ENV_FILE"
else
  echo "==> Reusing existing $ENV_FILE"
fi

# Keys added to the template after a box was first provisioned. The branch above
# only runs on a fresh install, so without this an existing deployment silently
# keeps the old settings and the new ones look applied because the script
# succeeded. Each entry is append-if-absent; nothing already set is overwritten.
add_env() {
  grep -q "^$1=" "$ENV_FILE" && return 0
  echo "==> Adding $1 to $ENV_FILE"
  printf '%s=%s\n' "$1" "$2" >> "$ENV_FILE"
}
# Without this the client dials 127.0.0.1:6379 inside the container, where
# nothing listens.
add_env REDIS_URL "redis://umay-redis:6379"
# shellcheck disable=SC1090
set -a; . "$ENV_FILE"; set +a

# ---- Database ----------------------------------------------------------------
if ! docker ps -a --format '{{.Names}}' | grep -qx umay-db; then
  echo "==> Creating umay-db (own volume, nothing published)"
  docker volume create umay_pgdata >/dev/null
  docker run -d --name umay-db --restart unless-stopped --network "$NETWORK" \
    -e POSTGRES_USER="$DB_USER" -e POSTGRES_PASSWORD="$POSTGRES_PASSWORD" -e POSTGRES_DB="$DB_NAME" \
    -v umay_pgdata:/var/lib/postgresql/data "$PG_IMAGE" >/dev/null
else
  echo "==> umay-db exists"
  docker start umay-db >/dev/null 2>&1 || true
fi

# ---- Cache -------------------------------------------------------------------
# The backend caches the child's last known location, the mother's BP
# calibration and geofence state here. It survives Redis being absent — the
# location read falls back to location_history and geofence debouncing falls
# back to in-process state — but "survives" is not "runs well": without this
# every map open is a table scan, and the log fills with ECONNREFUSED at the
# rate the client retries, which is where a real error would have to be seen.
#
# Its own container rather than the supabase-redis already on this box: that one
# belongs to a different stack, and sharing it would make an unrelated team's
# flushall our outage.
#
# No volume on purpose. Everything in here is derived data with a TTL, and the
# one piece that is not — geofence state — is designed to come back empty
# safely: an unknown previous position is never reported as a crossing.
if ! docker ps -a --format '{{.Names}}' | grep -qx umay-redis; then
  echo "==> Creating umay-redis"
  docker run -d --name umay-redis --restart unless-stopped --network "$NETWORK" \
    "$REDIS_IMAGE" redis-server --save "" --appendonly no --maxmemory 256mb \
    --maxmemory-policy allkeys-lru >/dev/null
else
  echo "==> umay-redis exists"
  docker start umay-redis >/dev/null 2>&1 || true
fi

echo "==> Waiting for Redis"
for i in $(seq 1 30); do
  docker exec umay-redis redis-cli ping 2>/dev/null | grep -q PONG && break
  [ "$i" = 30 ] && { echo "Redis never answered"; docker logs --tail 30 umay-redis; exit 1; }
  sleep 1
done

echo "==> Waiting for Postgres"
for i in $(seq 1 60); do
  docker exec umay-db pg_isready -U "$DB_USER" -d "$DB_NAME" >/dev/null 2>&1 && break
  [ "$i" = 60 ] && { echo "Postgres never became ready"; docker logs --tail 30 umay-db; exit 1; }
  sleep 2
done

# ---- Dependencies ------------------------------------------------------------
# No Node on the host; install inside the same image the service runs on so the
# native builds match.
if [ ! -d "$APP_DIR/node_modules" ] || [ "${FORCE_INSTALL:-0}" = 1 ]; then
  echo "==> npm ci (in $NODE_IMAGE)"
  docker run --rm -v "$APP_DIR:/app" -w /app "$NODE_IMAGE" npm ci --omit=dev --ignore-scripts 2>&1 | tail -5
fi

echo "==> Applying schema + migrations"
docker run --rm --network "$NETWORK" -v "$APP_DIR:/app" -w /app/packages/backend \
  -e DATABASE_URL="$DATABASE_URL" "$NODE_IMAGE" node db/apply.mjs 2>&1 | tail -12

# ---- Backend -----------------------------------------------------------------
# Recreated on every run so a git pull actually takes effect.
if docker ps -a --format '{{.Names}}' | grep -qx umay-backend; then
  echo "==> Replacing umay-backend"
  docker rm -f umay-backend >/dev/null
fi
echo "==> Starting umay-backend"
docker run -d --name umay-backend --restart unless-stopped --network "$NETWORK" \
  --env-file "$ENV_FILE" -v "$APP_DIR:/app" -w /app/packages/backend \
  "$NODE_IMAGE" npx tsx src/index.ts >/dev/null

echo "==> Waiting for the backend"
for i in $(seq 1 45); do
  if docker run --rm --network "$NETWORK" "$NODE_IMAGE" \
       wget -qO- http://umay-backend:8080/health >/dev/null 2>&1; then
    echo "    /health OK"; break
  fi
  [ "$i" = 45 ] && { echo "backend never answered:"; docker logs --tail 40 umay-backend; exit 1; }
  sleep 2
done

# The backend is designed to keep serving when the cache is unreachable, so a
# misconfigured REDIS_URL does not fail any check above — it just degrades
# quietly and floods the log. That is exactly how it went unnoticed until the
# log was read for another reason. Assert the client is actually connected.
if docker logs --tail 200 umay-backend 2>&1 | grep -q 'ECONNREFUSED 127.0.0.1:6379'; then
  echo "!!  the backend is still dialling 127.0.0.1:6379 — REDIS_URL did not reach it"
  echo "    env in container: $(docker exec umay-backend printenv REDIS_URL || echo '<unset>')"
  exit 1
fi
echo "    cache OK ($(docker exec umay-backend printenv REDIS_URL))"

echo
echo "==> Landing page self-check (as the proxy will see it)"
docker run --rm --network "$NETWORK" "$NODE_IMAGE" sh -c '
  wget -qO- http://umay-backend:8080/ | head -c 400000 > /tmp/p
  grep -q "<title>" /tmp/p && echo "    title      OK"
  grep -q "landing/a/" /tmp/p && echo "    assets     OK"
  grep -q "landing/wire.js" /tmp/p && echo "    form wired OK"
  printf "    bytes      %s\n" "$(wc -c < /tmp/p)"'

echo
docker ps --filter name=umay --format "    {{.Names}}  {{.Status}}"
echo
echo "Backend is up on the $NETWORK network as umay-backend:8080."
echo "It is NOT reachable from the internet yet — see deploy/landing-route.md."
