import { setStateRequest, setGoalsRequest, CameraControlType, setUserInfoRequest, phoneControlRequest, setHealthOpenRequest, setHeartRateControlRequest, setHeartRateControlWithOxygenRequest, Contact, setNotDisturbRequest, Clock, setLongSitRequest, setDrinkWaterRequest, sendMessageRequest, WeatherDay, musicControlRequest, EventReminder, setWeatherSevenRequest, setPasswordRequest, setFemaleHealthRequest, healthMeasureRequest, healthCalibrationRequest, SummerWorldClock, sportSyncToDeviceRequest, MessagePushSwitchRequest, SetSleepClocksRequest, syncTime, sendDialRequest, sendUiRequest, HealthInterval, HistoryType, BleFileSenderListener, Dial } from "./types";
declare class StarmaxSDK {
    private isSyncEnd;
    private syncDataList;
    private currentSyncCmd;
    private syncDataLength;
    private syncCmd;
    private taskList;
    errCodeMap: {
        1: string;
        2: string;
        3: string;
        4: string;
        5: string;
    };
    private static instance;
    private constructor();
    static getInstance(): StarmaxSDK;
    private bleRequest;
    private notifyData;
    notify(buffer: ArrayBuffer): Promise<any>;
    private getHistoryTypeCode;
    private extendBleRequest;
    private notifySync;
    private processSyncData;
    pair(): ArrayBuffer;
    pairGts10(usePopup: boolean): ArrayBuffer;
    getState(): ArrayBuffer;
    setState(obj: setStateRequest): ArrayBuffer;
    getGoals(): ArrayBuffer;
    setGoals(obj: setGoalsRequest): ArrayBuffer;
    findPhone(isFind: boolean): ArrayBuffer;
    blueSysPair(): ArrayBuffer;
    cameraControl(cameraControlType: CameraControlType): ArrayBuffer;
    getPower(): ArrayBuffer;
    getVersion(): ArrayBuffer;
    setTime(date: Date): ArrayBuffer;
    getHealthDetail(): ArrayBuffer;
    closeDevice(): ArrayBuffer;
    setUserInfo(obj: setUserInfoRequest): ArrayBuffer;
    setTimeOffset(offsetMinute: number): ArrayBuffer;
    getUserInfo(): ArrayBuffer;
    phoneControl(obj: phoneControlRequest): ArrayBuffer;
    setHealthOpen(obj: setHealthOpenRequest): ArrayBuffer;
    reset(): ArrayBuffer;
    getTime(): ArrayBuffer;
    getBtStatus(): ArrayBuffer;
    setBtStatus(isConnect: boolean): ArrayBuffer;
    setPPGOpen(openPPG: boolean): ArrayBuffer;
    getHealthOpen(): ArrayBuffer;
    clearLogo(): ArrayBuffer;
    setHeartRateAlarmThreshold(isOpen: boolean, threshold: number): ArrayBuffer;
    setDisplayMode(isDisplay: boolean): ArrayBuffer;
    setShipMode(isOpen: boolean): ArrayBuffer;
    setSportModeOnOff(isOpen: boolean, sportType: number): ArrayBuffer;
    setCustomBroadcast(interval: number, longTouchTime: number): ArrayBuffer;
    setDateFormat(isOrder: boolean): ArrayBuffer;
    unpair(unpairType: number): ArrayBuffer;
    setMessagePushOpen(obj: MessagePushSwitchRequest): ArrayBuffer;
    getMessagePushOpen(): ArrayBuffer;
    getHeartRateControl(): ArrayBuffer;
    getContacts(): ArrayBuffer;
    setContacts(contacts: Contact[]): ArrayBuffer;
    getSos(): ArrayBuffer;
    setSos(sos: Contact[]): ArrayBuffer;
    setHeartRateControl(obj: setHeartRateControlRequest): ArrayBuffer;
    setHeartRateControlWithOxygen(obj: setHeartRateControlWithOxygenRequest): ArrayBuffer;
    setNotDisturb(obj: setNotDisturbRequest): ArrayBuffer;
    getNotDisturb(): ArrayBuffer;
    getClocks(): ArrayBuffer;
    setClocks(clocks: Clock[]): ArrayBuffer;
    getLongSit(): ArrayBuffer;
    setLongSit(obj: setLongSitRequest): ArrayBuffer;
    getDrinkWater(): ArrayBuffer;
    setDrinkWater(obj: setDrinkWaterRequest): ArrayBuffer;
    sendMessage(obj: sendMessageRequest): ArrayBuffer;
    setWeather(weatherDays: Array<WeatherDay>): ArrayBuffer;
    musicControl(obj: musicControlRequest): ArrayBuffer;
    getEventReminder(): ArrayBuffer;
    setEventReminder(reminders: Array<EventReminder>): ArrayBuffer;
    getSportModes(): ArrayBuffer;
    setSportModes(modes: Array<number>): ArrayBuffer;
    getWeatherSeven(): ArrayBuffer;
    setWeatherSeven(obj: setWeatherSevenRequest): ArrayBuffer;
    getApps(): ArrayBuffer;
    setApps(apps: Array<number>): ArrayBuffer;
    getWorldClocks(): ArrayBuffer;
    setWorldClocks(citys: Array<number>): ArrayBuffer;
    getDialInfo(): ArrayBuffer;
    switchDial(dialId: number): ArrayBuffer;
    getPassword(): ArrayBuffer;
    setPassword(obj: setPasswordRequest): ArrayBuffer;
    getFemaleHealth(): ArrayBuffer;
    setFemaleHealth(obj: setFemaleHealthRequest): ArrayBuffer;
    healthMeasurements(obj: healthMeasureRequest): ArrayBuffer;
    healthCalibration(obj: healthCalibrationRequest): ArrayBuffer;
    getSummerWorldClock(): ArrayBuffer;
    setSummerWorldClock(summerWorldClocks: Array<SummerWorldClock>): ArrayBuffer;
    sportSyncToDevice(obj: sportSyncToDeviceRequest): ArrayBuffer;
    getSleepClock(): ArrayBuffer;
    setSleepClock(obj: SetSleepClocksRequest): ArrayBuffer;
    getSupportLanguages(): ArrayBuffer;
    getSportHistory(resend: boolean): ArrayBuffer;
    getStepHistory(obj: syncTime): ArrayBuffer;
    getHeartRateHistory(obj: syncTime): ArrayBuffer;
    getBloodPressureHistory(obj: syncTime): ArrayBuffer;
    getBloodOxygenHistory(obj: syncTime): ArrayBuffer;
    getPressureHistory(obj: syncTime): ArrayBuffer;
    getMetHistory(obj: syncTime): ArrayBuffer;
    getTempHistory(obj: syncTime): ArrayBuffer;
    getMaiHistory(obj: syncTime): ArrayBuffer;
    getBloodSugarHistory(obj: syncTime): ArrayBuffer;
    getSleepHistory(obj: syncTime): ArrayBuffer;
    getShakeHeadHistory(obj: syncTime): ArrayBuffer;
    getRespirationRateHistory(obj: syncTime): ArrayBuffer;
    getExerciseHistory(obj: syncTime): ArrayBuffer;
    getValidHistoryDates(historyType: HistoryType): ArrayBuffer;
    getX04HealthIntervals(): ArrayBufferLike;
    setX04HealthIntervals(healthIntervals: Array<HealthInterval>): ArrayBufferLike;
    sendDial(obj: sendDialRequest): ArrayBuffer;
    sendFile(chunkIndex: number, buffer: Uint8Array): ArrayBuffer;
    sendUi(obj: sendUiRequest): ArrayBuffer;
    sendFirmware(fileSize: number): ArrayBuffer;
    sendLogo(fileSize: number): ArrayBuffer;
    sendPgl(fileSize: number): ArrayBuffer;
    sendMp3(fileSize: number, eventIndex: number): ArrayBuffer;
    sendDiffHeader(headerData: Uint8Array): ArrayBuffer;
    sendDiffCheckcode(checkcode: Uint8Array): ArrayBuffer;
    sendDiffFile(fileData: Uint8Array): ArrayBuffer;
    sendDiffComplete(): ArrayBuffer;
    getDialList(model: string): Promise<Array<Dial>>;
}
export declare const starmaxSDK: StarmaxSDK;
declare class BleFileSender {
    static allFileData: Uint8Array;
    private static totalChunks;
    private static chunkIndex;
    private static fileChunks;
    private static successCount;
    private static fileSenderListener;
    private static sdk;
    private static checksumData;
    private static checksumSendIndex;
    private static checksumInfo;
    private static checksumIndex;
    static diffStatus: string;
    static initFile(fileData: ArrayBuffer, listener: BleFileSenderListener): void;
    private static initData;
    static onSuccess(): void;
    static updateSuccessCount(): void;
    static onProgress(): void;
    static onFailure(status: number): void;
    static sendFile(): void;
    static sendDiffHeader(): void;
    static sendDiffChecksum(): void;
    static sendDiffFile(): void;
    static sendDiffComplete(): void;
    static hasDiffNext(): boolean;
    static notifyDiff(data: number[]): void;
    private static crc16_byte;
    private static calculateChecksum;
}
export declare const bleFileSender: typeof BleFileSender;
export {};
