import { CalibrationValue, getVersionResponse, GetWorldClocksResponse, MessagePushSwitchResponse, NotifyType, PairResponse, PhoneControlResponse, WristDetachmentResponse, basicResponse, cameraControlResponse, getAppsResponse, getBatteryVResponse, getBtStatusResponse, getClocksResponse, getContactResponse, getDrinkWaterResponse, getEventReminderResponse, getFemaleHealthResponse, getHealthDetailResponse, getHealthOpenResponse, getHeartRateControlResponse, getLongSitResponse, getNotDisturbResponse, getPowerResponse, getSportModes, getStandAndExerciseResponse, getStateResponse, getTimeResponse, getUserInfoResponse, getSosResponse, HealthMeasureType, GetSleepClockResponse, SportSyncFromDeviceResponse, getX04HealthIntervalsResponse, getValidHistoryDatesResponse, getExerciseHistoryResponse, respirationRateHistory, shakeHeadHistoryResponse, sleepHistoryResponse, bloodSugarHistoryResponse, maiHistoryResponse, tempHistoryResponse, metHistoryResponse, pressureHistoryResponse, bloodOxygenHistoryResponse, bloodPressureHistoryResponse, stepHistoryResponse, heartRateHistoryResponse, getSportHistoryResponse } from "./types";
export declare function notifyPair(): basicResponse;
export declare function notifyPairGTS10(data: number[]): PairResponse;
export declare function notifyGetX04HealthIntervals(data: number[]): getX04HealthIntervalsResponse;
export declare function notifyGetValidHistoryDates(data: number[]): getValidHistoryDatesResponse;
export declare function notifyExerciseHistory(data: number[]): getExerciseHistoryResponse;
export declare function notifyRespirationRateHistory(data: number[]): respirationRateHistory;
export declare function notifyShakeHeadHistory(data: number[]): shakeHeadHistoryResponse;
export declare function notifySleepHistory(data: number[]): sleepHistoryResponse;
export declare function notifyBloodSugarHistory(data: number[]): bloodSugarHistoryResponse;
export declare function notifyMaiHistory(data: number[]): maiHistoryResponse;
export declare function notifyMusicControl(data: number[]): {
    type: NotifyType;
    status: number;
    musicControlType: number;
};
export declare function notifyTempHistory(data: number[]): tempHistoryResponse;
export declare function notifyMetHistory(data: number[]): metHistoryResponse;
export declare function notifyPressureHistory(data: number[]): pressureHistoryResponse;
export declare function notifyBloodOxygenHistory(data: number[]): bloodOxygenHistoryResponse;
export declare function notifyBloodPressureHistory(data: number[]): bloodPressureHistoryResponse;
export declare function notifyStepHistory(data: number[]): stepHistoryResponse;
export declare function notifyHeartRateHistory(data: number[]): heartRateHistoryResponse;
export declare function notifySetHealthOpen(): basicResponse;
export declare function notifySetBtStatus(): basicResponse;
export declare function notifyGetBtStatus(data: number[]): getBtStatusResponse;
export declare function notifyGetCustomOnOff(): {
    type: NotifyType;
    status: number;
};
export declare function notifySetPPGOpen(): basicResponse;
export declare function notifySetDateFormat(): basicResponse;
export declare function notifyWristDetachment(data: number[]): WristDetachmentResponse;
export declare function notifyBlueSysPair(): basicResponse;
export declare function notifyReset(): basicResponse;
export declare function notifyGetState(data: number[]): getStateResponse;
export declare function notifySetState(): basicResponse;
export declare function notifyGetPower(data: number[]): getPowerResponse;
export declare function notifyGetVersion(data: number[]): getVersionResponse;
export declare function notifySendFile(): basicResponse;
export declare function notifyCameraControl(data: number[]): cameraControlResponse;
export declare function notifyGetGoals(data: number[]): {
    type: NotifyType;
    status: number;
    steps: number;
    heat: number;
    distance: number;
};
export declare function notifySetGoals(): basicResponse;
export declare function notifyGetHealthDetail(data: number[]): getHealthDetailResponse;
export declare function notifyCloseDevice(): basicResponse;
export declare function notifySetTime(): basicResponse;
export declare function notifySetUserInfo(): basicResponse;
export declare function notifyGetUserInfo(data: number[]): getUserInfoResponse;
export declare function notifyFindPhone(data: number[]): {
    type: NotifyType;
    status: number;
    isFind: boolean;
};
export declare function notifySetTimeOffset(): basicResponse;
export declare function notifyClearLogo(): basicResponse;
export declare function notifySetHeartAlarm(): basicResponse;
export declare function notifySetDisplayMode(): basicResponse;
export declare function notifyPhoneControl(data: number[]): PhoneControlResponse;
export declare function notifySetShipMode(): basicResponse;
export declare function notifySetSportModeOnOff(): basicResponse;
export declare function notifySetCustomBroadcast(): basicResponse;
export declare function notifyGetBatteryV(data: number[]): getBatteryVResponse;
export declare function notifyUnpair(): basicResponse;
export declare function notifyGetTime(data: number[]): getTimeResponse;
export declare function notifyGetHealthOpen(data: number[]): getHealthOpenResponse;
export declare function notifyGetStandAndExercise(data: number[]): getStandAndExerciseResponse;
export declare function notifyGetHeartRateControl(data: number[]): getHeartRateControlResponse;
export declare function notifyGetSportModes(data: number[]): getSportModes;
export declare function notifySetWeatherSeven(): basicResponse;
export declare function notifyGetApps(data: number[]): getAppsResponse;
export declare function notifySetApps(): basicResponse;
export declare function notifyGetWorldClock(data: number[]): GetWorldClocksResponse;
export declare function notifyGetDials(data: number[]): {
    type: NotifyType;
    status: number;
    dialList: any[];
};
export declare function notifySwitchDial(): basicResponse;
export declare function notifySetSummerWorldClocks(): basicResponse;
export declare function notifyGetSummerWorldClocks(data: number[]): {
    type: NotifyType;
    status: number;
    clocks: any[];
};
export declare function notifySetSleepClock(): basicResponse;
export declare function notifyGetSleepClock(data: number[]): GetSleepClockResponse;
export declare function notifySetPassword(): basicResponse;
export declare function notifySportSyncToDevice(): basicResponse;
export declare function notifySportSyncFromDevice(data: number[]): SportSyncFromDeviceResponse;
export declare function notifyGetSupportLanguages(data: number[]): {
    type: NotifyType;
    status: number;
    languages: number[];
};
export declare function notifyGetMessagePushOpen(data: number[]): MessagePushSwitchResponse;
export declare function notifySendFileInfo(): basicResponse;
export declare function notifySetMessagePushOpen(): basicResponse;
export declare function notifyGetSportHistory(data: number[]): getSportHistoryResponse;
export declare function notifyHealthCalibration(data: number[]): {
    type: NotifyType;
    status: number;
    calibrateType: number;
    cmd: number;
    year: number;
    month: number;
    day: number;
    value: CalibrationValue[];
};
export declare function notifyGetPassword(data: number[]): {
    type: NotifyType;
    isOpen: boolean;
    password: string;
    status: number;
};
export declare function notifySetWorldClock(): basicResponse;
export declare function notifySetSportModes(): basicResponse;
export declare function notifySetHeartRateControl(): basicResponse;
export declare function notifySetContacts(): basicResponse;
export declare function notifySetFemaleHealth(): basicResponse;
export declare function notifyHealthMeasurement(data: number[]): {
    type: NotifyType;
    healthType: HealthMeasureType;
    status: number;
    value: number;
};
export declare function notifyGetFemaleHealth(data: number[]): getFemaleHealthResponse;
export declare function notifyGetEventReminder(data: number[]): getEventReminderResponse;
export declare function notifySetEventReminder(): basicResponse;
export declare function notifyGetSos(data: number[]): getSosResponse;
export declare function notifySetSos(): basicResponse;
export declare function notifyGetContacts(data: number[]): getContactResponse;
export declare function notifyGetNotDisturb(data: number[]): getNotDisturbResponse;
export declare function notifySetNotDisturb(): basicResponse;
export declare function notifyGetClocks(data: number[]): getClocksResponse;
export declare function notifySetClocks(): basicResponse;
export declare function notifySetLongSit(): basicResponse;
export declare function notifyGetLongSit(data: number[]): getLongSitResponse;
export declare function notifySetDrinkWater(): basicResponse;
export declare function notifyGetDrinkWater(data: number[]): getDrinkWaterResponse;
export declare function notifySetWeather(): basicResponse;
export declare function notifySendMessage(): basicResponse;
export declare function notifyDiff(data: number[]): {
    status: number;
    type: NotifyType;
    data: number[];
};
